### ISSUE TITLE
Wrong indentation when `insert` after a `create table` inside a `create function`

### ISSUE THREAD

**Issue by LaetitiaJV** [darold/pgFormatter#119]
Hi,

It seems that `pg_format` doesn't indent correctly an `insert` statement after a `create table` statement inside a `create function statement.

Here is my test file:

```sql
create or replace function foo_bar ()
  returns void
  as $$
begin
  create table if not exists foo (
      id_foo INTEGER,
      id_bar INTEGER
    );
    insert into foo
      values (1, 2);
end;
$$
language plpgsql
security definer;
```
After launching a simple `pg_format` on it (without any parameter), output is:

```sql
CREATE OR REPLACE FUNCTION foo_bar ()
    RETURNS void
    AS $$
BEGIN
    CREATE TABLE IF NOT EXISTS foo (
        id_foo INTEGER,
        id_bar INTEGER
    );
        INSERT INTO foo
        VALUES (1, 2);
END;
$$
LANGUAGE plpgsql
SECURITY DEFINER;
```

It seems to me that it should be :

```sql
CREATE OR REPLACE FUNCTION foo_bar ()
    RETURNS void
    AS $$
BEGIN
    CREATE TABLE IF NOT EXISTS foo (
        id_foo INTEGER,
        id_bar INTEGER
    );
    INSERT INTO foo
        VALUES (1, 2);
end;
$$
LANGUAGE plpgsql
SECURITY DEFINER;
```
Am I right ?

**Comment by darold** [comment]
You are right. It seems that it is fixed in latest release v4.0. I'm traveling without possibility to update the online demo site but you can download it from https://github.com/darold/pgFormatter/releases

I will update the site and send an announce for the new version tomorrow. Here is the output with last version:
```
CREATE OR REPLACE FUNCTION foo_bar ()
    RETURNS void
    AS $$
BEGIN
    CREATE TABLE IF NOT EXISTS foo (
        id_foo INTEGER,
        id_bar INTEGER
    );
    INSERT INTO foo
    VALUES (1, 2);
$$
LANGUAGE plpgsql
SECURITY DEFINER;
```

**Comment by LaetitiaJV** [comment]
Thanks for your quick answer.

that's weird because with version 4.0, I still have the same issue:
```
$ pg_format --version
pg_format version 4.0
$ pg_format /tmp/test_format.sql
CREATE OR REPLACE FUNCTION foo_bar ()
    RETURNS void
    AS $$
BEGIN
    CREATE TABLE IF NOT EXISTS foo (
        id_foo INTEGER,
        id_bar INTEGER
    );
        INSERT INTO foo
        VALUES (1, 2);
        END;
$$
LANGUAGE plpgsql
SECURITY DEFINER;
```

**Comment by darold** [comment]
Here is my result:
```
CREATE OR REPLACE FUNCTION foo_bar ()
    RETURNS void
    AS $$
BEGIN
    CREATE TABLE IF NOT EXISTS foo (
        id_foo INTEGER,
        id_bar INTEGER
    );
    INSERT INTO foo
    VALUES (1, 2);
        END;
$$
LANGUAGE plpgsql
SECURITY DEFINER;
```
I have missed the END statement in previous example and it is not at the right place, but the INSERT statement is at the right indentation level. Will check what going wrong.

**Comment by darold** [comment]
Commit 54078da fixes this issue.

**Comment by LaetitiaJV** [comment]
Works like a chram! Thank you!
