### ISSUE TITLE
CASE ELSE indentation in function/block

### ISSUE THREAD

**Issue by temoto** [darold/pgFormatter#164]
Case's `ELSE` gets dedented to beginning of line instead of previous level.

```sql
CREATE OR REPLACE FUNCTION task_job_maint_after ()
    RETURNS TRIGGER
    AS $$
BEGIN
    CASE new.state
    WHEN 'final' THEN
        NOTIFY task_job_final;
ELSE
    NULL;
    END CASE;
    RETURN NEW;
    END;
$$
LANGUAGE plpgsql;
```

**Comment by darold** [comment]
Fixed in commit f987456

**Comment by ejabu** [comment]
![image](https://user-images.githubusercontent.com/2019630/74387710-dc038580-4e2b-11ea-8224-ad45991e6b21.png)

I still get this.

``` sql
SELECT
    tar.mor_sk AS mor_id2,
    avi.mor_sk AS mor_id,
    avi.region_sk AS prov_id,
    avi.district_sk AS district_id,
    mor.mor_short AS mor_name,
    prov.region_name AS prov_name,
    INITCAP(dist.district_name) AS district_name,
    dist.longitude AS district_lng,
    dist.latitude AS district_lat,
    avi.plant_sk AS plant_id,
    -- mdp.depot_sk as plant_id,
    mdp.plant_id AS plant_code,
    mdp.plant_name AS plant_name,
    'dppu' AS plant_type,
    mdp.latitude AS lat,
    mdp.longitude AS lng,
    mdp.address AS address,
    mdp.phone AS phone,
    avi.customer_sk AS customer_id,
    mcs.customer_id AS customer_code,
    mcs.customer_name AS customer_name,
    -- mcs.all_customer_sk -- recheck,
    avi.material_sk AS product_id,
    mmt.material_id AS product_code,
    mmt.material_name AS product_name,
    -- mmt.material_sk,
    avi.amount AS sales,
    tar.volume_in_kl AS sales_target,
    CASE WHEN tar.volume_in_kl > 0 THEN
    (avi.amount / tar.volume_in_kl * 100)
ELSE
    0
    END AS sales_perf
FROM
    avi_list avi
    LEFT JOIN master_customer mcs ON avi.customer_sk = mcs.all_customer_sk
    LEFT JOIN master_material mmt ON avi.material_sk = mmt.material_sk
    LEFT JOIN master_depot mdp ON avi.plant_sk = mdp.plant_sk
    LEFT JOIN mor_list mor ON mor.mor_sk = avi.mor_sk
    LEFT JOIN prov_list prov ON prov.region_sk = avi.region_sk
    LEFT JOIN dist_list dist ON dist.district_sk = avi.district_sk
    LEFT JOIN target tar ON 1 = 1
```

**Comment by ejabu** [comment]
![image](https://user-images.githubusercontent.com/2019630/74413544-31628580-4e72-11ea-9e54-fc3c16c00f30.png)

I noticed , it will work if I change 

``` sql

    (avi.amount / tar.volume_in_kl * 100)
```

to 
```
1111
```

Is this as expected ?
